import { useState } from 'react';
import { Network, ArrowLeft, Sparkles, Layers, GitBranch } from 'lucide-react';
import { Link } from 'react-router-dom';
import ReportViewer from '../components/ReportViewer/ReportViewer';
import LiveAnalysisPanel from '../components/LiveAnalysisPanel/LiveAnalysisPanel';
import { architectureReport } from '../data/sampleReports';
import { isLiveModeEnabled } from '../utils/api';

export default function ArchitectureMap() {
  const [liveReport, setLiveReport] = useState<{ content: string; metadata: any } | null>(null);
  const liveModeEnabled = isLiveModeEnabled();

  const handleDownload = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleLiveAnalysisSuccess = (content: string, metadata: any) => {
    setLiveReport({ content, metadata });
    setTimeout(() => {
      document.getElementById('live-report')?.scrollIntoView({ behavior: 'smooth' });
    }, 100);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <Link to="/" className="inline-flex items-center text-primary-600 hover:text-primary-700 mb-6">
        <ArrowLeft className="h-4 w-4 mr-2" />
        Back to Dashboard
      </Link>

      <div className="bg-white rounded-lg shadow-md p-8 mb-6">
        <div className="flex items-center space-x-4 mb-6">
          <div className="bg-purple-100 p-3 rounded-lg">
            <Network className="h-8 w-8 text-purple-600" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Architecture Map</h1>
            <p className="text-gray-600">Visualize system architecture and component relationships</p>
          </div>
        </div>

        <div className="border-t border-gray-200 pt-6">
          <div className="bg-purple-50 border border-purple-200 rounded-lg p-6 mb-6">
            <div className="flex items-start space-x-3">
              <Sparkles className="h-5 w-5 text-purple-600 mt-0.5" />
              <div>
                <h3 className="font-semibold text-purple-900 mb-2">Bob Mode: Plan Mode</h3>
                <p className="text-sm text-purple-800">
                  Bob analyzes the codebase structure and creates comprehensive architecture documentation 
                  showing major components, their interactions, data flow, and design patterns.
                </p>
              </div>
            </div>
          </div>

          {/* Live Analysis Panel */}
          {liveModeEnabled && (
            <div className="mb-6">
              <LiveAnalysisPanel
                workflowId="architecture-map"
                onSuccess={handleLiveAnalysisSuccess}
              />
            </div>
          )}

          {/* Live Report */}
          {liveReport && (
            <div id="live-report" className="mb-6">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Live Analysis Result</h2>
              <div className="bg-green-50 rounded-lg p-4 border border-green-200 mb-4">
                <div className="flex items-center justify-between mb-2">
                  <div>
                    <p className="text-sm font-medium text-green-900">
                      Generated by: IBM Bob (Live)
                    </p>
                    <p className="text-xs text-green-700">
                      Repository: {liveReport.metadata.repository} •
                      Branch: {liveReport.metadata.branch}
                    </p>
                  </div>
                </div>
              </div>
              <ReportViewer
                content={liveReport.content}
                title="Live Architecture Map"
                onDownload={() => handleDownload(liveReport.content, 'live-architecture-map.md')}
              />
            </div>
          )}

          {/* What This Workflow Does */}
          <div className="mb-6">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">What This Workflow Does</h2>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <h4 className="font-semibold text-gray-900 mb-2">Input</h4>
                <ul className="space-y-2 text-sm text-gray-700">
                  <li className="flex items-start">
                    <span className="text-purple-600 mr-2">•</span>
                    <span>Repository codebase</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-purple-600 mr-2">•</span>
                    <span>Configuration files</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-purple-600 mr-2">•</span>
                    <span>Dependency manifests</span>
                  </li>
                </ul>
              </div>
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <h4 className="font-semibold text-gray-900 mb-2">Output</h4>
                <ul className="space-y-2 text-sm text-gray-700">
                  <li className="flex items-start">
                    <span className="text-purple-600 mr-2">•</span>
                    <span>Component diagram with relationships</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-purple-600 mr-2">•</span>
                    <span>Data flow visualization</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-purple-600 mr-2">•</span>
                    <span>Design patterns identification</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-purple-600 mr-2">•</span>
                    <span>Scalability considerations</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* How It Speeds Up Development */}
          <div className="mb-6">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">How It Speeds Up Development</h2>
            <div className="grid md:grid-cols-3 gap-4">
              <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-lg p-4 border border-purple-200">
                <Layers className="h-6 w-6 text-purple-600 mb-2" />
                <h4 className="font-semibold text-gray-900 mb-1">System Understanding</h4>
                <p className="text-sm text-gray-700">
                  Grasp complex architectures in minutes, not days
                </p>
              </div>
              <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-lg p-4 border border-purple-200">
                <GitBranch className="h-6 w-6 text-purple-600 mb-2" />
                <h4 className="font-semibold text-gray-900 mb-1">Impact Analysis</h4>
                <p className="text-sm text-gray-700">
                  Understand how changes affect other components
                </p>
              </div>
              <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-lg p-4 border border-purple-200">
                <Network className="h-6 w-6 text-purple-600 mb-2" />
                <h4 className="font-semibold text-gray-900 mb-1">Better Decisions</h4>
                <p className="text-sm text-gray-700">
                  Make informed architectural choices with full context
                </p>
              </div>
            </div>
          </div>

          {/* Sample Output */}
          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-4">
              {liveModeEnabled ? 'Demo Sample Output' : 'Sample Generated Output'}
            </h2>
            <div className="bg-gray-50 rounded-lg p-4 border border-gray-200 mb-4">
              <div className="flex items-center justify-between mb-2">
                <div>
                  <p className="text-sm font-medium text-gray-900">
                    Generated by: {architectureReport.generatedBy}
                  </p>
                  <p className="text-xs text-gray-600">
                    Repository: {architectureReport.metadata?.repository} • 
                    Files analyzed: {architectureReport.metadata?.filesAnalyzed}
                  </p>
                </div>
              </div>
            </div>
            <ReportViewer
              content={architectureReport.content}
              title={architectureReport.title}
              onDownload={() => handleDownload(architectureReport.content, 'architecture-map.md')}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

// Made with Bob
