import { Report, RiskReport, DocGapReport } from '../types/report';

export const repoOnboardingReport: Report = {
  id: 'onboarding-001',
  title: 'E-Commerce Platform Onboarding Guide',
  workflowId: 'repo-onboarding',
  generatedBy: 'IBM Bob (Ask Mode)',
  timestamp: '2024-01-15T10:30:00Z',
  metadata: {
    repository: 'acme-corp/ecommerce-platform',
    branch: 'main',
    filesAnalyzed: 247
  },
  content: `# E-Commerce Platform Onboarding Guide

## Project Overview

**Purpose**: A modern, scalable e-commerce platform built with microservices architecture, supporting multi-tenant operations, real-time inventory management, and seamless payment processing.

**Tech Stack**: Node.js, React, PostgreSQL, Redis, Docker, Kubernetes

**Key Features**:
- Multi-tenant product catalog
- Real-time inventory synchronization
- Payment gateway integration (Stripe, PayPal)
- Order management and fulfillment
- Customer authentication and profiles
- Admin dashboard with analytics

## Repository Structure

\`\`\`
ecommerce-platform/
├── services/              # Microservices
│   ├── catalog/          # Product catalog service
│   ├── inventory/        # Inventory management
│   ├── orders/           # Order processing
│   ├── payments/         # Payment gateway integration
│   └── users/            # User authentication & profiles
├── frontend/             # React web application
├── shared/               # Shared libraries
├── infrastructure/       # Deployment configs
└── docs/                # Documentation
\`\`\`

## Development Workflow

### Initial Setup

1. **Prerequisites**: Node.js 18+, Docker Desktop, PostgreSQL 14+, Redis 7+
2. **Clone and Install**: \`git clone && npm install\`
3. **Environment Configuration**: \`cp .env.example .env\`
4. **Start Development**: \`docker-compose up -d && npm run dev\`

### Common Commands

- \`npm run dev\` - Start all services
- \`npm run test\` - Run all tests
- \`npm run lint\` - Check code quality
- \`npm run build\` - Build production bundles

## First Contribution Steps

1. Pick a good first issue (labeled \`good-first-issue\`)
2. Create feature branch: \`git checkout -b feature/your-feature\`
3. Make changes following style guide
4. Write tests for new functionality
5. Submit PR with clear description

---

*Generated by IBM Bob (Ask Mode) - Repository analysis completed in 2.3 seconds*`
};

export const architectureReport: Report = {
  id: 'architecture-001',
  title: 'E-Commerce Platform Architecture Map',
  workflowId: 'architecture-map',
  generatedBy: 'IBM Bob (Plan Mode)',
  timestamp: '2024-01-15T11:00:00Z',
  metadata: {
    repository: 'acme-corp/ecommerce-platform',
    branch: 'main',
    filesAnalyzed: 247
  },
  content: `# E-Commerce Platform Architecture Map

## System Overview

The platform follows a **microservices architecture** with event-driven communication, designed for scalability, maintainability, and independent service deployment.

## Component Diagram

\`\`\`
┌─────────────────────────────────────────────────────────────┐
│                        API Gateway                           │
│                    (Kong / Express)                          │
└────────────┬────────────────────────────────────────────────┘
             │
    ┌────────┴────────┐
    │                 │
    ▼                 ▼
┌─────────┐      ┌─────────┐
│ Frontend│      │ Mobile  │
│ (React) │      │  App    │
└─────────┘      └─────────┘
                      │
    ┌─────────────────┴─────────────────┬──────────────┐
    │                 │                  │              │
    ▼                 ▼                  ▼              ▼
┌─────────┐     ┌──────────┐     ┌──────────┐   ┌──────────┐
│ Catalog │     │Inventory │     │  Orders  │   │ Payments │
│ Service │     │ Service  │     │ Service  │   │ Service  │
└────┬────┘     └────┬─────┘     └────┬─────┘   └────┬─────┘
     │               │                 │              │
     └───────────────┴─────────────────┴──────────────┘
                                       │
                                       ▼
                            ┌──────────────────┐
                            │  Message Queue   │
                            │   (RabbitMQ)     │
                            └──────────────────┘
\`\`\`

## Core Components

### 1. API Gateway
- Single entry point for all client requests
- JWT token validation
- Rate limiting (100 req/min per user)
- Request routing to microservices

### 2. Catalog Service
- Product CRUD operations
- Category management
- Search and filtering
- Multi-tenant product isolation

### 3. Inventory Service
- Real-time stock tracking
- Reservation system
- Low stock alerts
- Multi-warehouse support

### 4. Orders Service
- Order lifecycle management
- State machine: PENDING → CONFIRMED → PROCESSING → SHIPPED → DELIVERED
- Event publications for order state changes

### 5. Payments Service
- Stripe/PayPal integration
- Payment processing
- Refund handling
- PCI compliance

## Design Patterns

1. **API Gateway Pattern** - Single entry point
2. **Database per Service** - Data isolation
3. **Event Sourcing** - Audit trail
4. **CQRS** - Separate read/write models
5. **Circuit Breaker** - Fault tolerance

## Scalability Considerations

- Horizontal scaling for all services
- Read replicas for databases
- Redis caching layer
- CDN for static assets
- Auto-scaling based on metrics

---

*Generated by IBM Bob (Plan Mode) - Architecture analysis completed in 3.7 seconds*`
};


export const docGapReport: DocGapReport = {
  id: 'docgap-001',
  title: 'Documentation Gap Analysis',
  workflowId: 'doc-gap-finder',
  generatedBy: 'IBM Bob (Ask Mode)',
  timestamp: '2024-01-15T11:30:00Z',
  summary: {
    totalGaps: 12,
    high: 4,
    medium: 5,
    low: 3
  },
  gaps: [
    {
      priority: 'high',
      category: 'API Documentation',
      title: 'Missing API endpoint documentation for Payments Service',
      description: 'The Payments Service has 8 API endpoints but only 3 are documented. Critical endpoints like /api/v1/payments/refund are undocumented.',
      location: 'services/payments/src/routes/',
      recommendation: 'Add OpenAPI/Swagger documentation for all payment endpoints. Include request/response schemas, authentication requirements, and error codes.'
    },
    {
      priority: 'high',
      category: 'Setup Instructions',
      title: 'Incomplete environment variable documentation',
      description: 'The .env.example file is missing 12 required environment variables including STRIPE_WEBHOOK_SECRET and REDIS_CLUSTER_NODES.',
      location: '.env.example',
      recommendation: 'Audit all services for environment variable usage and update .env.example with complete list, descriptions, and example values.'
    },
    {
      priority: 'high',
      category: 'Code Comments',
      title: 'Complex business logic lacks inline documentation',
      description: 'The order state machine has complex transition logic with no explanatory comments.',
      location: 'services/orders/src/stateMachine.ts',
      recommendation: 'Add comprehensive inline comments explaining each state transition, edge cases, and business rules.'
    },
    {
      priority: 'medium',
      category: 'Testing',
      title: 'Missing test coverage documentation',
      description: 'No documentation exists explaining the testing strategy or coverage requirements.',
      location: 'docs/',
      recommendation: 'Create docs/TESTING.md with testing guidelines, coverage targets (80%+), and how to run tests.'
    },
    {
      priority: 'medium',
      category: 'Security',
      title: 'Security best practices not documented',
      description: 'No documentation for JWT token handling, API key rotation, or secure coding guidelines.',
      location: 'docs/',
      recommendation: 'Create docs/SECURITY.md covering authentication flows, authorization patterns, and secret management.'
    },
    {
      priority: 'low',
      category: 'Code Comments',
      title: 'Utility functions lack JSDoc comments',
      description: 'The shared/utils/ directory has 23 utility functions with no JSDoc comments.',
      location: 'shared/utils/',
      recommendation: 'Add JSDoc comments to all utility functions with parameter descriptions and usage examples.'
    }
  ],
  metadata: {
    repository: 'acme-corp/ecommerce-platform',
    filesAnalyzed: 247
  }
};

export const testPlanReport: Report = {
  id: 'testplan-001',
  title: 'Test Plan for Payment Refund Feature',
  workflowId: 'test-plan-generator',
  generatedBy: 'IBM Bob (Code Mode)',
  timestamp: '2024-01-15T12:00:00Z',
  metadata: {
    repository: 'acme-corp/ecommerce-platform',
    branch: 'feature/payment-refunds',
    filesAnalyzed: 8
  },
  content: `# Test Plan: Payment Refund Feature

## Overview

**Feature**: Payment refund processing for orders
**Test Coverage Target**: 85%+

## Unit Tests

### 1. RefundController Tests

**TC-1.1: Create Full Refund - Success**
\`\`\`typescript
it('should create full refund for valid order', async () => {
  const response = await request(app)
    .post('/api/v1/refunds')
    .send({ orderId: 'order-123', amount: 99.99, reason: 'Customer request' })
    .set('Authorization', 'Bearer valid-token');
  
  expect(response.status).toBe(201);
  expect(response.body.refund.status).toBe('pending');
});
\`\`\`

**TC-1.2: Create Partial Refund** - Test 50% refund
**TC-1.3: Invalid Order ID** - Expect 404 error
**TC-1.4: Insufficient Authorization** - Expect 403 Forbidden
**TC-1.5: Already Refunded** - Test idempotency
**TC-1.6: Amount Exceeds Total** - Expect 400 Bad Request

### 2. RefundService Tests

**TC-2.1: Process Stripe Refund - Success**
**TC-2.2: Network Failure** - Test retry logic (3 attempts)
**TC-2.3: Insufficient Funds** - Handle Stripe error
**TC-2.4: Calculate Full Refund** - Include tax and shipping
**TC-2.5: Calculate Partial Refund** - Proportional calculation
**TC-2.6: Validate Eligibility** - 30-day window check

## Integration Tests

### 3. End-to-End Refund Flow

**TC-3.1: Complete Refund Flow**
- Create order → Process payment → Request refund
- Verify order status updated
- Verify Stripe refund created

**TC-3.2: Partial Refund Multiple Times**
- Refund 30% → Refund 20%
- Verify cumulative tracking
- Ensure cannot exceed 100%

**TC-3.3: Refund Webhook Processing**
- Simulate Stripe webhook
- Verify signature validation
- Ensure idempotent processing

## Edge Cases

**TC-4.1: Refund During Payment Processing** - Expect 409 Conflict
**TC-4.2: Refund After Partial Shipment** - Only unshipped items
**TC-4.3: Refund with Expired Payment Method** - Still processes
**TC-4.4: Refund with Promotional Discount** - Correct calculation

## Performance Tests

**TC-5.1: Concurrent Refund Processing** - 100 concurrent requests
**TC-5.2: API Response Time** - Target < 500ms (p95)

## Security Tests

**TC-6.1: Unauthorized Refund Attempt** - Expect 403
**TC-6.2: SQL Injection** - Verify input sanitization
**TC-6.3: Rate Limiting** - Expect 429 after threshold

## Success Criteria

- ✅ All unit tests pass (85%+ coverage)
- ✅ All integration tests pass
- ✅ Performance targets met
- ✅ Security tests pass

---

*Generated by IBM Bob (Code Mode) - Test plan created in 4.2 seconds*`
};

export const riskReport: RiskReport = {
  id: 'risk-001',
  title: 'Security & Code Quality Risk Assessment',
  workflowId: 'risk-review',
  generatedBy: 'IBM Bob (Review Mode)',
  timestamp: '2024-01-15T12:30:00Z',
  summary: {
    totalIssues: 15,
    critical: 2,
    high: 5,
    medium: 6,
    low: 2
  },
  risks: [
    {
      severity: 'critical',
      category: 'Security',
      title: 'Hardcoded Stripe API key in source code',
      description: 'The Stripe secret key is hardcoded in services/payments/src/config/stripe.ts instead of being loaded from environment variables.',
      location: 'services/payments/src/config/stripe.ts:12',
      recommendation: 'Move API key to environment variables. Use process.env.STRIPE_SECRET_KEY. Rotate the exposed key immediately.'
    },
    {
      severity: 'critical',
      category: 'Security',
      title: 'SQL injection vulnerability in search endpoint',
      description: 'Product search uses string concatenation to build SQL queries, making it vulnerable to SQL injection.',
      location: 'services/catalog/src/controllers/searchController.ts:45-52',
      recommendation: 'Replace with parameterized queries using prepared statements. Add input validation and sanitization.'
    },
    {
      severity: 'high',
      category: 'Security',
      title: 'Missing JWT token expiration validation',
      description: 'Authentication middleware validates signatures but not expiration, allowing expired tokens indefinitely.',
      location: 'services/users/src/middleware/auth.ts:28-35',
      recommendation: 'Add expiration check. Set 1-hour expiration. Implement refresh token mechanism.'
    },
    {
      severity: 'high',
      category: 'Security',
      title: 'Insufficient rate limiting on authentication',
      description: 'Login endpoints have no rate limiting, vulnerable to brute force attacks.',
      location: 'services/users/src/routes/auth.ts',
      recommendation: 'Implement rate limiting: 5 attempts per 15 minutes. Add CAPTCHA after 3 failed attempts.'
    },
    {
      severity: 'high',
      category: 'Performance',
      title: 'N+1 query problem in order listing',
      description: 'Order listing makes separate queries for each order\'s items, causing severe performance issues.',
      location: 'services/orders/src/controllers/orderController.ts:120-135',
      recommendation: 'Use JOIN or eager loading to fetch orders with items in single query. Add database indexes.'
    },
    {
      severity: 'medium',
      category: 'Code Quality',
      title: 'Complex function exceeds 100 lines',
      description: 'processOrder function is 187 lines with nested conditionals, difficult to maintain.',
      location: 'services/orders/src/services/orderService.ts:45-232',
      recommendation: 'Refactor into smaller functions with single responsibilities. Aim for functions under 50 lines.'
    },
    {
      severity: 'medium',
      category: 'Performance',
      title: 'Missing database indexes',
      description: 'Orders table queried by user_id and status frequently but lacks indexes.',
      location: 'services/orders/migrations/',
      recommendation: 'Add composite index on (user_id, status). Add index on created_at for date queries.'
    },
    {
      severity: 'low',
      category: 'Code Quality',
      title: 'Inconsistent naming conventions',
      description: 'Mix of camelCase and kebab-case in file names.',
      location: 'services/*/src/',
      recommendation: 'Standardize on camelCase for files and functions. Document in style guide.'
    }
  ],
  metadata: {
    repository: 'acme-corp/ecommerce-platform',
    branch: 'main',
    filesAnalyzed: 247
  }
};

export const prPackReport: Report = {
  id: 'prpack-001',
  title: 'PR Package: Payment Refund Feature',
  workflowId: 'pr-pack-generator',
  generatedBy: 'IBM Bob (Code Mode)',
  timestamp: '2024-01-15T13:00:00Z',
  metadata: {
    repository: 'acme-corp/ecommerce-platform',
    branch: 'feature/payment-refunds',
    filesAnalyzed: 12
  },
  content: `# Pull Request: Payment Refund Feature

## 📋 PR Title
\`feat(payments): Add payment refund processing with Stripe integration\`

## 🎯 Description

This PR implements a complete payment refund system, allowing customers to request refunds and administrators to process them through Stripe.

### What Changed
- Added refund API endpoints for creating and managing refunds
- Integrated Stripe refund API with retry logic and error handling
- Implemented refund state machine with proper status transitions
- Added event-driven communication for order status updates
- Created comprehensive test suite with 87% coverage

### Why This Change
- **Customer Satisfaction**: Enables hassle-free refund process
- **Operational Efficiency**: Automates refund workflow
- **Compliance**: Meets payment processor requirements
- **Revenue Protection**: Proper refund tracking prevents fraud

## 🔗 Related Issues

Closes #234 - Implement payment refund functionality

## 📝 Changelog

### Added
- Refund API endpoints (POST, GET, PUT /api/v1/refunds)
- Stripe integration with automatic retry (3 attempts)
- Partial and full refund support
- Refund eligibility validation (30-day window)
- Database schema for refunds table

### Changed
- Order service now listens to refund events
- Payment service error handling improved
- API documentation updated

### Tests
- 45 unit tests added
- 12 integration tests added
- Test coverage: 87% (target: 85%)

## ✅ Testing Evidence

### Manual Testing
- ✅ Created full refund for $99.99 order
- ✅ Created partial refund (50%) for $200 order
- ✅ Verified Stripe dashboard shows refunds
- ✅ Confirmed order status updates correctly
- ✅ Tested error scenarios (invalid order, expired token)

### Automated Testing
\`\`\`bash
npm run test
# 57 tests passed, 0 failed
# Coverage: 87.3%
\`\`\`

## 👀 Reviewer Checklist

Please verify:
- [ ] Refund API endpoints work as expected
- [ ] Stripe integration handles errors gracefully
- [ ] Database migrations run successfully
- [ ] Test coverage meets 85% threshold
- [ ] API documentation is complete
- [ ] No hardcoded secrets or API keys
- [ ] Error messages are user-friendly
- [ ] Event publishing works correctly

## 🚀 Deployment Notes

### Database Migration
\`\`\`bash
npm run migrate
# Creates refunds table with indexes
\`\`\`

### Environment Variables
Add to .env:
\`\`\`
STRIPE_REFUND_WEBHOOK_SECRET=whsec_xxx
REFUND_WINDOW_DAYS=30
\`\`\`

### Rollback Plan
If issues occur:
1. Revert database migration: \`npm run migrate:rollback\`
2. Disable refund endpoints in API Gateway
3. Monitor Stripe dashboard for pending refunds

## 📊 Performance Impact

- API response time: < 300ms (p95)
- Database queries optimized with indexes
- No impact on existing endpoints

---

*Generated by IBM Bob (Code Mode) - PR package created in 3.1 seconds*`
};

// Made with Bob
// Made with Bob